# Generated by Django 3.2 on 2022-08-01 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0003_auto_20220802_0419'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons', to='references.groups')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_lessons', to='references.pair')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_lessons', to='references.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_lessons', to='references.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
