# Generated by Django 3.2 on 2022-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20220802_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pair',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
