# Generated by Django 3.2 on 2023-01-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20220802_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ('index',)},
        ),
    ]
